version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .docker.env

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: >
      sh -c 'python manage.py test'

  db:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    command: -p 5433

volumes:
  postgres_data:
