version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5433
    command: >
      sh -c "make start"

  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    command: -p 5433
    expose:
      - "5433"

volumes:
  postgres_data:
