# Generated by Django 4.2.1 on 2023-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('reference', models.CharField(max_length=6, unique=True)),
                ('date', models.DateField()),
                (
                    'amount',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')],
                        max_length=10,
                    ),
                ),
                ('category', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
