# Generated by Django 4.2.1 on 2023-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('reference', 'user_email')},
        ),
    ]
